name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: cargoacr.azurecr.io
        username: ${{ secrets.AZURE_AD_CLIENT_ID }}
        password: ${{ secrets.AZURE_AD_CLIENT_SECRET}}
    - run: |
        docker build -t cargoacr.azurecr.io/myappgithun:${{ github.sha }} .
