---
  name: CICD-DotNet
  on:
    push:
      branches:
        - main
  jobs:
    build-and-deploy:
      runs-on: windows-latest
      defaults:
        run:
          working-directory: ./Dot
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install.NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: "6.0"
        - name: Build project
          run: dotnet build -c Release

        - name: Build project
          run: dotnet test -c Release

        - name: Publish project
          run: dotnet publish -c Release -o publish

        - name: Publish Artifact
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: $GITHUB_WORKSPACE
        - name: Verify artifact
          run: |
            dir $GITHUB_WORKSPACE
  