name: CICD-DotNet

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install.NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Restore NuGet packages
        working-directory: '/DotNetCode'
        run: dotnet restore

      - name: Build project
        working-directory: '/DotNetCode'
        run: dotnet build -c Release

      - name: Publish project
        working-directory: '/DotNetCode'
        run: dotnet publish -c Release -o publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          package: publish
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
