name: Build and deploy .NET Core app to Azure Web App

env:
  AZURE_WEBAPP_NAME: cargowebapp
  AZURE_WEBAPP_PACKAGE_PATH: '$(System.DefaultWorkingDirectory)/**/*.zip'
  DOTNET_VERSION: '6.0'

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: './Dot'

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and package
        run: |
          dotnet build -c Release
          dotnet publish -c Release -o $GITHUB_WORKSPACE/app

      - name: Create deployment package
        run: |
          cd $GITHUB_WORKSPACE/app
          zip -r $GITHUB_WORKSPACE/app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: $GITHUB_WORKSPACE/app.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}