name: CICD-DotNet
on:
  push:
    branches:
    - main
  #workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: mamodemo
jobs:
  build-and-deploy:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: './Dot'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install.NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Current Directory 1
        run: |
          dir $GITHUB_WORKSPACE
          
      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build project
        run: dotnet build -c Release

      - name: Publish project
        run: dotnet publish -c Release -o publish
      
      - name: Current Directory 2
        run: |
          dir $GITHUB_WORKSPACE
          dir D:\a\githubactions-20240515\githubactions-20240515\Dot\bin\Release\net5.0

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: D:\a\githubactions-20240515\githubactions-20240515\Dot\bin\Release\net5.0
          #path: ./my-project/bin/Release/net6.0/my-project.dll

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cargowebapp'
          package: './my-artifact.zip'
#      - name: Current Directory 3
#        run: |
#          dir $GITHUB_WORKSPACE      
#      - uses: actions/upload-artifact@v4
#        id: artifact-upload-step
#        with:
#          name: my-artifact
#          path: path/to/artifact/content/