name: 'Terraform'
on:
  workflow_dispatch:
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  # Checkout the respository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4.1.1
  # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
          terraform_version: 1.6.6
## Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
#    - name: Terraform Init
#      id: init
#      run: terraform init -backend-config="storage_account_name=stog01" -backend-config="container_name=stgct01" -backend-config="resource_group_name=Free Trial"
#
## Run a terraform plan 
#    - name: Terraform Plan
#      id: plan
#      run: terraform plan -no-color
#
## On workflow dispatch build or change infrastructure according to Terraform configuration files
#    - name: Terraform Apply
#      run: terraform apply -auto-approve
